### PR TITLE
Add support for Fortran files

### PR DESCRIPTION
**Pull request by ZedThree**
Applies slightly modified patch from
https://sourceforge.net/p/doxymacs/patches/12/
Original author: https://sourceforge.net/u/fiolj/profile/

### CODE REVIEW

**Comment by pniedzielski** [comment]
I apologize for the delay, I'll review this tonight.  Thanks again.

**Comment by pniedzielski** [comment]
I've reviewed the code, and it looks good.  I've also compiled and played with it; it seems to work with all the major features of `doxymacs` and doesn't cause any regressions.  I've been working on a test suite using ERT, so I will start adding Fortran tests to it as well.

Do you want attribution as Peter Hill or ZedThree?

**Comment by ZedThree** [comment]
Excellent, cheers! Peter Hill is fine.

**Comment by pniedzielski** [comment]
Merged with commit e159981.

**Pull request closed without merging**
